name:  camera
description: camera plugin of iConceive

version: 1.0.0 

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.11